// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbmavrlmzmpbwulcvrzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNibWF2cmxtem1wYnd1bGN2cnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyOTY0MjQsImV4cCI6MjA4ODg3MjQyNH0.OPFvDzURQAtsWP-D_KihLJ0P48dk55d7Fhhj8EuDMxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});